# docker-compose.yml

services:
  db:
    image: mysql:8.4
    container_name: chefitup-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chefitupdb
      MYSQL_USER: chefitupuser
      MYSQL_PASSWORD: chefituppass
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
